title: Hamza Warriach  # your name (or website title) here
logo: "images/picture_portfolio.jpg?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Python Connoisseur
  <br><br>
  Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/hwarriach/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
